name: 'Create Tag and Pre-release'
description: 'Creates a tag and a pre-release on GitHub with release notes'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

  build_version:
    description: 'Build version'
    required: true

outputs:
  release_id:
    description: 'The ID of the created release'
    value: ${{ steps.prepare_pre_release.outputs.release_id }}

runs:
  using: 'composite'
  steps:
    - name: Get last tag
      id: get_last_tag
      uses: jhonnyvargasarias/actions/get-last-tag@main
      with:
        github_token: ${{ inputs.github_token }}

    - name: Get commit range since last tag
      id: get_commit_range
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const lastTag = JSON.parse('${{ steps.get_last_tag.outputs.last_tag }}');

          const response = lastTag
            ? (
              await github.rest.repos.compareCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base: lastTag.commit.sha,
                head: context.sha,
              })
            )
            : (
              await github.rest.repos.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
              })
            );

          let rawCommits = response.data;

          if (lastTag) {
            rawCommits = response.data.commits.length > 0 
              ? response.data.commits 
              : [response.data.base_commit];
          }
          console.log('lastTag', JSON.stringify(lastTag))
          console.log('rawCommits', JSON.stringify(rawCommits))
          const commits = rawCommits.map((commit) => ({
            sha: commit.sha.slice(0, 7),
            author: `@${commit.author.login}`,
            message: JSON.stringify(commit.commit.message),
          }))

          core.setOutput('commits', JSON.stringify(commits));

    - name: Prepare release notes
      id: prepare_release_notes
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const commitsJson = '${{ steps.get_commit_range.outputs.commits }}';
          const commits = JSON.parse(commitsJson);

          let releaseNotes = '## Release Information\n';
          releaseNotes += '| Author       | Commit          | Message            |\n';
          releaseNotes += '|--------------|-----------------|--------------------|\n';
          for (const commit of commits) {
            releaseNotes += `| ${commit.author} | ${commit.sha} | ${commit.message} |\n`;
          }

          core.setOutput('release_notes', releaseNotes);

    - name: Create tag
      id: create-tag
      uses: jhonnyvargasarias/actions/create-tag@main
      with:
        build_version: ${{ inputs.build_version }}
        github_token: ${{ inputs.github_token }}

    - name: Prepare pre-release
      id: prepare_pre_release
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const version = `${{ inputs.build_version }}`;
          const releaseNotes = ${{ toJson(steps.prepare_release_notes.outputs.release_notes) }};

          const { data } = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: version,
            name: `v${version}`,
            body: releaseNotes,
            prerelease: true,
            draft: false,
          });

          core.setOutput('release_id', data.id);
