name: 'Get Last Tag'
description: 'Get the last tag from the repository as JSON'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

outputs:
  last_tag:
    description: 'The last tag from the repository as JSON'
    value: ${{ steps.get_last_tag.outputs.last_tag }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Get last tag
      id: get_last_tag
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { data: tags } = await github.rest.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1,
          });

          const lastTag = tags.length > 0 && tags[0] ? tags[0] : '';
          core.setOutput('last_tag', JSON.stringify(lastTag));
