name: 'Create Tag'
description: 'Creates a tag on GitHub'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

  build_version:
    description: 'Build version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Create tag
      id: create_tag
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const lastTag = core.getInput('last_tag');
          const buildVersion = core.getInput('build_version');

          const { data: tag } = await github.rest.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: buildVersion,
            message: `Release ${buildVersion}`,
            object: context.sha,
            type: 'commit',
          });

          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${buildVersion}`,
            sha: tag.sha,
          });
