name: 'Workflow for testing an action'

on: [push]

permissions:
  contents: write
  deployments: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create tag
        id: create-tag
        uses: ./create-tag
        with:
          build_version: '1.0.0'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create-pre-release:
    runs-on: ubuntu-latest
    needs: create-tag
    outputs:
      release_id: ${{ steps.create-pre-release-step.outputs.release_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create pre-release
        id: create-pre-release-step
        uses: ./create-pre-release
        with:
          build_version: '1.0.0'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-pre-release-to-release:
    runs-on: ubuntu-latest
    needs: create-pre-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update pre-release to release
        uses: ./update-pre-release-to-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ needs.create-pre-release.outputs.release_id }}
