name: 'Workflow for testing an action'

# on: [push]
on: [workflow_dispatch]

permissions:
  contents: write
  deployments: write

jobs:
  generate-next-version:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.generate-next-version.outputs.next_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: generate-next-version
        uses: jhonnyvargasarias/actions/generate-next-version@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_patch_version: 10
          max_minor_version: 10

  create-tag-and-pre-release:
    runs-on: ubuntu-latest
    needs: generate-next-version
    outputs:
      release_id: ${{ steps.create-tag-and-pre-release-step.outputs.release_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag and pre-release
        id: create-tag-and-pre-release-step
        uses: jhonnyvargasarias/actions/create-tag-and-pre-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_version: ${{ needs.generate-next-version.outputs.next_version }}

  update-pre-release-to-release:
    runs-on: ubuntu-latest
    needs: create-tag-and-pre-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update pre-release to release
        uses: jhonnyvargasarias/actions/update-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ needs.create-tag-and-pre-release.outputs.release_id }}
          prerelease: false
          draft: false

  delete-release:
    runs-on: ubuntu-latest
    needs:
      [
        generate-next-version,
        create-tag-and-pre-release,
        update-pre-release-to-release,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete release
        uses: jhonnyvargasarias/actions/delete-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ needs.create-tag-and-pre-release.outputs.release_id }}

      - name: Delete tag
        uses: jhonnyvargasarias/actions/delete-tag@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_version: ${{ needs.generate-next-version.outputs.next_version }}
