name: 'Workflow for testing an action'

# on: [push]
on: [workflow_dispatch]

permissions:
  contents: write
  deployments: write

jobs:
  generate-next-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        uses: ./generate-next-version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_patch_version: 10
          max_minor_version: 10

  # create-tag-and-pre-release:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     release_id: ${{ steps.create-tag-and-pre-release-step.outputs.release_id }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Create tag and pre-release
  #       id: create-tag-and-pre-release-step
  #       uses: ./create-tag-and-pre-release
  #       with:
  #         build_version: '1.0.0'
  #         github_token: ${{ secrets.GITHUB_TOKEN }}

  # update-pre-release-to-release:
  #   runs-on: ubuntu-latest
  #   needs: create-tag-and-pre-release
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Update pre-release to release
  #       uses: ./update-pre-release-to-release
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         release_id: ${{ needs.create-tag-and-pre-release.outputs.release_id }}
