name: 'Delete Release'
description: 'Deletes a release in a GitHub repository'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

  release_id:
    description: 'Release ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update release
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const releaseId = `${{ inputs.release_id }}`;

          await github.rest.repos.deleteRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: releaseId,
          });
